### ISSUE TITLE
Switch from gammabytehosting/rockylinux to official image

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-rockylinux8-ansible#1]
So far, glancing at Docker Hub, Quay, and https://rockylinux.org/download, I don't see any 'official' Rocky Linux Docker image to build from. So I'm currently using `gammabytehosting/rockylinux`, which seemed the best choice of few options on Docker Hub (outside of building my own image from scratch using the RC ISO—don't want to do that).

I want to see if there will be an official Docker image, and switch to that.

**Comment by NeilHanlon** [comment]
Workin' on it ☺

**Comment by geerlingguy** [comment]
RC is out now: https://hub.docker.com/r/rockylinux/rockylinux

**Comment by geerlingguy** [comment]
Noting that:

  - There isn't a `latest` tag, which means I'll lock in to rc tag for now. Ideally they'll pop a latest tag on the rolling latest image version in the future.
  - There is only an amd64 image available currently (so has to build non-native on my new Macs, ha!).

**Comment by jorp** [comment]
Hey Jeff, we have official images of 8.4 stable on [Docker Hub](https://hub.docker.com/r/rockylinux/rockylinux) and [Quay](https://quay.io/repository/rockylinux/rockylinux) now!

**Comment by geerlingguy** [comment]
@jorp - Yep! I have switched to the official `8` tag on Docker Hub as of this morning. Congrats and thanks!!!
