### ISSUE TITLE
Ansible hostvars missing 'ansible_default_ipv4'?

### ISSUE THREAD

**Issue by pigay** [geerlingguy/docker-rockylinux8-ansible#2]
Hi Jeff,

First, I want to thank you for all your amzing work. I learnt so much from you!

My question:

I want to use your docker-rockylinux8-ansible image with molecule to test an ansible role I'm developing.

I need to gather all molecule scenario instances IP addresses to make network communications possible. With other docker images (your docker-centos8-ansible for example) I use the hostvars `ansible_default_ipv4.address`, like in the following:
```yaml
- name: dbg
  debug:
    msg: "{{ hostvars[item].ansible_default_ipv4.address }}"
  loop: "{{ groups['all'] }}"
```

But with rockylinux8, it fails with a `'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_default_ipv4'`.

Do you think it is related to the RockyLinux official distribution or to ansible itself?

Thanks in advance.

Pierre

**Comment by geerlingguy** [comment]
What version of Ansible are you using? It might be the variable is in a new location—check what's available with just `hostvars[item]` first.

**Comment by pigay** [comment]
I'm using 2.10.5. I also tried with a fresh 2.12.1.

I can't find any IP address in 'hostvars[item]'...

**Comment by pigay** [comment]
Didn't manage to make this work.
I workarounded by using ansible docker module to get thoses addresses directly.
