### ISSUE TITLE
Rocky 8 not working with Ansible 2.17

### ISSUE THREAD

**Issue by dgibbs64** [geerlingguy/docker-rockylinux8-ansible#6]
Hi Jeff,

Just wanted to let you know that the Rocky image is no longer working since the upgrade to Ansible 2.17. I believe this is due to the deprecation of Python 3.6 in Ansible 2.17 https://docs.ansible.com/ansible/latest/roadmap/ROADMAP_2_17.html . Seems like an odd choice as this effectively breaks RHEL 8 support in ansible https://github.com/ansible/ansible/issues/82068

It appears that many parts of RHEL8 rely on Python 3.6 such as DNF. So it would mean only some  modules work.

**Comment by geerlingguy** [comment]
Ugh... sounds similar to the whole 'Python doesn't really work in CentOS 7' thing that plagued a lot of my testing back in the day, before I had upgraded everything.

Just another reason I'm glad I've moved all my personal servers over to Debian / Ubuntu, heh. Though any older release (I believe Ubuntu 18.04 is also hit by this) is not in wonderful shape.

**Comment by dgibbs64** [comment]
I am honestly baffled by this choice. It feels like a lack of comms between the Ansible and RHEL teams. I think this might have significant impact for RedHat enterprise customers once they catch up to 2.17. I am trying to seek some clarity though multiple channels currently. Hopefuly we get an official response soon on how org's should manage this (or even better if RH find a resolution). I will try and keep you posted 😅

**Comment by konstruktoid** [comment]
One option is of course _not_ to update to Ansible 2.17, 2.16 will be EOL in May 2025 (https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) so there's time to upgrade any affected systems or for RHEL (and related distributions) to address the situation.

**Comment by dgibbs64** [comment]
The problem is that RHEL-8 doesn't go full EOL until May, 2029. So what this does it force orgs to upgrade to RHEL-9 sooner or eventually use an unsupported ansible version. I would have thought that 2 products owned by the same company would have parity in managing support between its products. Which is why I am waiting for advice from RH directly on what strategy the org I work for should take. i.e should we now be planning in RHEL-9 upgrades sooner because we rely on ansible. I am hoping that someone at RH clocks on to the issue and the Ansible and RHEL teams figure out a way forward. I would hope they find a way to get `ansible.builtin.dnf` working again.

**Comment by dgibbs64** [comment]
@geerlingguy We got an answer from an ansible core dev. The takeaway I get is Ansible support for RHEL-8 ends at 2.16 (unless you don't need package management). https://github.com/ansible/ansible/issues/83357#issuecomment-2150254754

**Comment by dgibbs64** [comment]
2.16 will be supported with security updates downstream until RHEL-8 EOL. However it still creates an issue for me as I now have to redo my molecule tests to test against 2.16 and >= 2.17. As least they provided some clarity.

**Comment by geerlingguy** [comment]
@dgibbs64 - I get the Ansible team's between a rock and a hard place with that—for my own community stuff, I don't want to pin versions if I don't have to... but considering that's an official answer, at least for this repo, I'd be okay pinning to 2.16.x.

**Comment by dgibbs64** [comment]
@geerlingguy I have already begun updating my molecule tests (that are based on yours). Here is my current update that excludes rocky8 and opensuse from 2.17. Here is some of the code you might find useful https://github.com/dgibbs64/ansible-role-netdata/blob/main/.github/workflows/molecule.yml

I am very glad they provided clarity on the best way forward

**Comment by geerlingguy** [comment]
Hopefully this fixes things up: https://github.com/geerlingguy/docker-rockylinux8-ansible/commit/f70421a05d2bab86be07a95f3bd85051ab1a7631

Though it does mean this image will run an unsupported version of Ansible moving forward. It'd be nice if there were LTS's of community editions but that is not something I expect, the community team already does heroic work with the constraints they're under.
